
---
apiVersion: v1
kind: Namespace
metadata:
  name: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    {{- if .Values.infra_nodes }}
    openshift.io/node-selector: node-role.kubernetes.io/infra=
    scheduler.alpha.kubernetes.io/defaultTolerations: >-
      [{"operator": "Exists", "effect": "NoSchedule", "key":
      "node-role.kubernetes.io/infra"}]
    {{- end }}
