apiVersion: v2
appVersion: v2.4.15
description: A Helm chart for customising the deployment of the Red Hat GitOps Operator 🔫
name: gitops-operator
version: 0.4.8
home: https://github.com/redhat-cop/helm-charts
icon: https://raw.githubusercontent.com/eformat/openshift-gitops/main/rh-gitops.png
maintainers:
- name: eformat
- name: springdo
