# IPA Server must know it's own hostname to work properly....
# These values will probs need to be overwritten or could use lookup function?
# app_domain: apps.mycluster.example.com
admin_password: Passw0rd

cluster_name: springdo.sandbox1422
domain: opentlc.com

# sensible defaults
image: freeipa-server:rhel-7
install_opts: "-U --setup-dns --no-forwarders --no-ntp"
container_args: "ipa-server-install"
volume: 5Gi

# this can be used if not using helm install to set the correct ns
# namespaceOverride: ipa

# this example is using the ldap admin user and password as the bind creds
# and expects a group in ldap called `student`
# disabled by default so as to not overwrite existing oauth configs in openshift-config ns
ocp_auth:
  enabled: false
  bind_dn: "uid=admin,cn=users,cn=accounts"
  bind_password: Passw0rd
  base: "cn=student,cn=groups,cn=accounts"

machineconfig:
  ignition_version: 3.2.0

# assumes node-role.kubernetes.io/infra: "" on one or more nodes
runOnInfra: false
