# IPA Server must know it's own hostname to work properly....
# these must be set in line with whats in the cluster !!
app_domain: apps.mycluster.example.com
admin_password: Passw0rd123
realm: "-r redhatlabs.dev"

# sensible defaults
image: freeipa-server:rhel-7
install_opts: "-U --setup-dns --no-forwarders --no-ntp"
container_args: "ipa-server-install"
volume: 5Gi

# this can be used if not using helm install to set the correct ns
# namespaceOverride: ipa

# this example is using the ldap admin user and password as the bind creds
# and expects a group in ldap called `student`
# disabled by default so as to not overwrite existing oauth configs in openshift-config ns
ocp_auth:
  enabled: false
  bind_dn: "uid=ldap_admin,cn=users,cn=accounts,dc=redhatlabs,dc=dev"
  bind_password: Passw0rd
  base: "cn=student,cn=groups,cn=accounts,dc=redhatlabs,dc=dev"
  domain: "dc=redhatlabs,dc=dev"

machineconfig:
  ignition_version: 3.2.0

# assumes node-role.kubernetes.io/infra: "" on one or more nodes
runOnInfra: false
