apiVersion: v2
name: openshift-logforwarding-splunk
description: Log Forwarding from OpenShift to Splunk
version: 0.0.4
maintainers:
  - email: andy.block@gmail.com
    name: sabre1041
home: https://github.com/redhat-cop/helm-charts
