# turn on verbose logging for config job
verbose: false

# stackrox configuration
stackrox:
  clusterName: do500
  namespace: stackrox
  analyzer:
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 100m