# turn on verbose logging for config job
verbose: false

operatorhub:
  enabled: true
  namespace: openshift-operators
  operators:
    - name: rhacs-operator
      subscription:
        channel: latest
        approval: Automatic
        operatorName: rhacs-operator
        sourceName: redhat-operators
        sourceNamespace: openshift-marketplace

# stackrox configuration
stackrox:
  clusterName: tl500
  namespace: stackrox
  analyzer:
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 100m
