operators:
- channel: stable
  installPlanApproval: Manual
  name: external-secrets-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  csv: external-secrets-operator.v0.8.1
