{{- if and (not .Values.forwarding.splunk.insecure) .Values.forwarding.splunk.ca_bundle -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openshift-logforwarding-splunk.fullname" . }}-splunk
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: splunk
{{ include "openshift-logforwarding-splunk.labels" . | indent 4 }}
type: Opaque
data:
    splunk-ca.crt: {{ .Values.forwarding.splunk.ca_bundle | b64enc }}
{{ end }}
