{{- if .Values.ocp_auth.enabled }}
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster2
  namespace: openshift-config
spec:
  identityProviders:
  - name: FreeIPA
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - displayName
        preferredUsername:
        - uid
      bindDN: {{ .Values.ocp_auth.bind_dn }}
      bindPassword:
        name: {{ include "ipa.fullname" . }}-bind-password
      insecure: true
      url: ldap://{{ include "ipa.fullname" . }}.{{ include "ipa.namespace" . }}.svc.cluster.local:389/{{ .Values.ocp_auth.base }}?uid
{{- end }}