---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "ipa.fullname" . }}
  labels:
    {{- include "ipa.labels" . | nindent 4 }}
  annotations:
    description: Route for FreeIPA server's HTTPS
spec:
  host: {{ include "ipa.fullname" . }}-{{ include "ipa.namespace" . }}.apps.{{ .Values.cluster_name }}.{{ .Values.domain }}
  to:
    kind: Service
    name: {{ include "ipa.fullname" . }}
  port:
    targetPort: https
  tls:
    termination: passthrough
