---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "ipa.fullname" . }}
  labels:
    {{- include "ipa.labels" . | nindent 4 }}
  annotations:
    description: Route for FreeIPA server's HTTPS
spec:
  host: {{ .Values.hostname }}
  to:
    kind: Service
    name: {{ include "ipa.fullname" . }}
  port:
    targetPort: https
  tls:
    termination: passthrough
