
{{- if .Values.createOperatorGroup }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "operators-installer.labels" $ | nindent 4 }}
spec:
  targetNamespaces:
  - {{ .Release.Namespace }}
{{- end }}
