{{- range $namespace := (include "operators-installer.uniqueNamespaces" $ | fromJsonArray) }}
---
# create one installplan-approver Role per unqiue namespace operators are being installed in
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: installplan-approver
  namespace: {{ $namespace }}
  labels:
    {{- include "operators-installer.labels" $ | nindent 4 }}
  {{- if $.Values.approveManualInstallPlanViaHook }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"
  {{- end }}
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - installplans
  - subscriptions
  verbs:
  - get
  - list
  - patch
{{- end }}
