{{- range .Values.operators }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
spec:
  channel: {{ .channel }}
  installPlanApproval: {{ .installPlanApproval }}
  name: {{ .name }}
  source: {{ .source }}
  sourceNamespace: {{ .sourceNamespace }}
  startingCSV: {{ .csv }}
{{- end }}