---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: is-allowed-development
  namespace: {{ .Values.application.environments.cicd }}
spec:
  params:
    - name: revision-type
  check:
    image: registry.redhat.io/openshift4/ose-cli:latest@sha256:767a5fb58229f519ad61e4f1e78d84eb017d356702a5a16ab23b948b90db27c1
    script: | 
      #!/bin/sh
      if [ "$(params.revision-type)" == "feature" ] || [ "$(params.revision-type)" == "develop" ]; then
        exit 0
      else 
        exit 1
      fi
---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: is-allowed-production
  namespace: {{ .Values.application.environments.cicd }}
spec:
  params:
    - name: revision-type
  check:
    image: registry.redhat.io/openshift4/ose-cli:latest@sha256:767a5fb58229f519ad61e4f1e78d84eb017d356702a5a16ab23b948b90db27c1
    script: | 
      #!/bin/sh 
      if [ "$(params.revision-type)" == "release" ] || [ "$(params.revision-type)" == "hotfix" ] || [ "$(params.revision-type)" == "patch" ]; then
        exit 0
      else 
        exit 1
      fi