name: Lint Test

on: 
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        fetch-depth: 0

    - name: Setup Helm 🧰
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3
      with:
        version: v3.5.1

    - name: Setup Python 🐍
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
      with:
        python-version: 3.7

    - name: Setup chart-testing 🧰
      uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

    - name: Run Chart lint tests 🧪
      run: ct lint
