apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: gitea
    app.kubernetes.io/component: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: gitea
  name: gitea
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/gpte-devops-automation/gitea:latest
    from:
      kind: DockerImage
      name: quay.io/gpte-devops-automation/gitea:latest
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local
status: {}